# Generated by Django 5.0.1 on 2024-02-01 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0008_alter_status_description_alter_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Недопустимые символы. Используйте только кириллицу, латиницу, цифры и некоторые спец символы.', regex='^[а-яА-Яa-zA-Z0-9\\s_.,!@#&*()-+=;:]*$')]),
        ),
    ]
