# Generated by Django 5.0.1 on 2024-02-01 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0010_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Недопустимые символы. Используйте только кириллицу, латиницу, цифры и некоторые спец символы.', regex='^[a-zA-Z]+$')]),
        ),
    ]
