# Generated by Django 5.0.1 on 2024-02-01 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0018_alter_status_description_alter_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(validators=[django.core.validators.RegexValidator(code='invalid_date', message='Недопустимый формат. Введите дату в формате dd-mm-yyy', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateField(validators=[django.core.validators.RegexValidator(code='invalid_date', message='Недопустимый формат. Введите дату в формате dd-mm-yyy', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
    ]
