# Generated by Django 5.0.1 on 2024-02-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0020_alter_task_date_end_alter_task_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_tracker.user'),
        ),
    ]
