# Generated by Django 5.0.1 on 2024-05-12 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0025_status_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Invalid characters. Use only Cyrillic, Latin, digits, and some special characters.', regex='^[а-яА-Яa-zA-Z]*$'), django.core.validators.MaxLengthValidator(50, message='Field length should not exceed 50 characters.')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_surname', message='Invalid characters. Use only Cyrillic, Latin, digits, and some special characters.', regex='^[а-яА-Яa-zA-Z]*$'), django.core.validators.MaxLengthValidator(50, message='Field length should not exceed 50 characters.')], verbose_name='surname'),
        ),
    ]
