# Generated by Django 5.0.1 on 2024-05-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0026_alter_customuser_name_alter_customuser_surname'),
    ]

    operations = [
    ]
