# Generated by Django 5.0.1 on 2024-05-12 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0027_auto_20240512_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.task'),
        ),
        migrations.AlterField(
            model_name='status_task',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.user'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.user'),
        ),
    ]
